import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import style from './style.module.scss'
import Header from "./_components/Header/header";
import Footer from "./_components/Footer/footer";
import { ClerkProvider } from "@clerk/nextjs";
import "@uploadthing/react/styles.css";
 
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" className={style.appHtml}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
  );
}
